update to neoforge 1.20.4

diff --git a/.github/workflows/crowdin_upload.yml b/.github/workflows/crowdin_upload.yml
--- a/.github/workflows/crowdin_upload.yml
+++ b/.github/workflows/crowdin_upload.yml
@@ -1,34 +1,48 @@
-name: Crowdin Upload
+name: Upload lang keys to Crowdin
 
 on:
+  workflow_dispatch:
   push:
     branches:
-      - 1.16
-      - 1.18
-      - 1.19
+      - '1.[0-9]+'
+      - '1.[0-9]+.[0-9]+'
     paths:
       - 'src/main/resources/assets/wallets/lang/en_us.json'
 
 jobs:
-  upload-source-files:
-    name: Upload Source Files
+  upload-translations:
+    environment: Testing
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Crowdin Upload
-        uses: crowdin/github-action@1.4.14
+      - uses: actions/checkout@v4
+      - name: Setup Java JDK
+        uses: actions/setup-java@v4
         with:
-          upload_sources: true
-          upload_language: 'en'
-          auto_approve_imported: true
-          add_crowdin_branch: ${{ github.ref_name }}
-          crowdin_branch_name: ${{ github.ref_name }}
-          config: ./crowdin.yml
-          project_id: 492617
-          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
+          java-version: '17'
+          distribution: 'adopt'
+          cache: 'gradle'
+      - name: Determine Crowdin branch
+        id: get_crowdin_branch
+        run: |
+          output=$(./gradlew crowdinBranch)
+          version=$(echo "$output" | grep -oP 'Crowdin branch: \K\d+\.\d+')
+          if [[ $version =~ ^1\.[0-9]+$ ]]; then
+            echo "Crowdin branch: $version"
+            echo "crowdin_branch=$version" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid version: $version"
+            exit 1
+          fi
+      - name: Upload translation keys
+        uses: crowdin/github-action@v1
+        with:
+          crowdin_branch_name: ${{ steps.get_crowdin_branch.outputs.crowdin_branch }}
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          CROWDIN_PROJECT_ID: walletsmc
-          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
+          CROWDIN_KEY: ${{ secrets.CROWDIN_KEY }}
+      - name: Install Crowdin CLI
+        run: npm i -g @crowdin/cli
+      - name: Pre-translate
+        run: crowdin pre-translate -b ${{ steps.get_crowdin_branch.outputs.crowdin_branch }} --translate-with-perfect-match-only --translate-untranslated-only --method=tm
+        env:
+          CROWDIN_KEY: ${{ secrets.CROWDIN_KEY }}
diff --git a/.github/workflows/publish-release.yml b/.github/workflows/publish-release.yml
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -1,40 +1,107 @@
-name: Publish Release
+name: Publish
 
 on:
   push:
     tags:
       - v*
   workflow_dispatch:
-
-
+    inputs:
+      versionType:
+        description: 'Version Type'
+        required: true
+        default: 'alpha'
+        type: choice
+        options:
+          - alpha
+          - beta
+          - release
+      additionalVersionInfo:
+        description: 'Additional Version Info. Only relevant for beta versions.'
+        required: false
+        default: ''
+        type: string
+      changelog:
+        description: 'Changelog added to Curseforge and Modrinth'
+        required: false
+        default: ''
+        type: string
 
 permissions:
   contents: read
 
 jobs:
-  publish-release:
-    environment: Release
+  determine-environment:
     runs-on: ubuntu-latest
-
+    outputs:
+      environment: ${{ steps.get_environment.outputs.environment }}
+      version: ${{ steps.get_environment.outputs.version }}
     steps:
-      - uses: actions/checkout@v3
-      - name: Check Tag
-        id: check-tag
+      - uses: actions/checkout@v4
+      - name: Determine Environment
+        id: get_environment
         run: |
-          if [[ ${{ github.event_name }} = workflow_dispatch ]]; then
-            echo ::set-output name=match::true
-          elif [[ ${{ github.event.ref }} =~ refs\/tags\/v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)-(0|[1-9]\d*)\.(0|[1-9]\d*) ]]; then
-            echo ::set-output name=match::true
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            if [[ "${{ github.event.inputs.versionType }}" == 'alpha' ]]; then
+              echo "environment=Testing" >> $GITHUB_OUTPUT
+              echo "version=alpha" >> $GITHUB_OUTPUT
+            elif [[ "${{ github.event.inputs.versionType }}" == 'beta' ]]; then
+              echo "environment=Testing" >> $GITHUB_OUTPUT
+              echo "version=beta=${{ github.event.inputs.additionalVersionInfo }}" >> $GITHUB_OUTPUT
+            elif [[ "${{ github.event.inputs.versionType }}" == 'release' ]]; then
+              echo "environment=Release" >> $GITHUB_OUTPUT
+              echo "version=release" >> $GITHUB_OUTPUT
+            fi
+          elif [[ ${{ github.event.ref }} =~ refs\/tags\/v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)-(0|[1-9]\d*)\.(0|[1-9]\d*) ]]; then
+            echo "environment=Release" >> $GITHUB_OUTPUT
+            echo "version=release" >> $GITHUB_OUTPUT
           fi
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        if: steps.check-tag.outputs.match == 'true'
+
+  determine-crowdin-branch:
+    runs-on: ubuntu-latest
+    outputs:
+      crowdin_branch: ${{ steps.get_crowdin_branch.outputs.crowdin_branch }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Setup Java JDK
+        uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'adopt'
           cache: 'gradle'
-      - name: Publish
-        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
-        if: steps.check-tag.outputs.match == 'true'
+      - name: Determine Crowdin branch
+        id: get_crowdin_branch
+        run: |
+          output=$(./gradlew crowdinBranch)
+          version=$(echo "$output" | grep -oP 'Crowdin branch: \K\d+\.\d+')
+          if [[ $version =~ ^1\.[0-9]+$ ]]; then
+            echo "Crowdin branch: $version"
+            echo "crowdin_branch=$version" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid version: $version"
+            exit 1
+          fi
+
+  publish:
+    runs-on: ubuntu-latest
+    needs: [determine-crowdin-branch, determine-environment]
+    environment: ${{ needs.determine-environment.outputs.environment }}
+    if: needs.determine-environment.outputs.version != '' && needs.determine-environment.outputs.environment != ''
+
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
         with:
-          arguments: build publish curseforge modrinth -PMAVEN_URL=${{ secrets.MAVEN_URL }} -PMAVEN_USER=${{ secrets.MAVEN_USER }} -PMAVEN_TOKEN=${{ secrets.MAVEN_TOKEN }} -PCURSEFORGE_API=${{ secrets.CURSEFORGE_API }} -PCROWDIN_KEY=${{ secrets.CROWDIN_KEY }} -PMODRINTH_API=${{ secrets.MODRINTH_API }} -Prelease
+          java-version: '17'
+          distribution: 'adopt'
+          cache: 'gradle'
+      - name: Install Crowdin CLI
+        run: npm i -g @crowdin/cli
+      - name: Download translations
+        run: crowdin download -b ${{ needs.determine-crowdin-branch.outputs.crowdin_branch }}
+        env:
+          CROWDIN_KEY: ${{ secrets.CROWDIN_KEY }}
+      - name: Publish
+        uses: gradle/gradle-build-action@v2.7.0
+        with:
+          arguments: publishAll -PMAVEN_URL=${{ secrets.MAVEN_URL }} -PMAVEN_USER=${{ secrets.MAVEN_USER }} -PMAVEN_TOKEN=${{ secrets.MAVEN_TOKEN }} -PCURSEFORGE_API=${{ secrets.CURSEFORGE_API }} -PMODRINTH_API=${{ secrets.MODRINTH_API }} -P${{ needs.determine-environment.outputs.version }}
